version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "todo-backend-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-13eyy5cvixhzu"
s3_prefix = "todo-backend-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
